name: Generate 3D Contribution Graph

on:
  # Run every Sunday at 00:00 UTC (weekly)
  schedule:
    - cron: "0 0 * * 0"
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub Contribution Graph
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: github-profile-3d-contrib/package-lock.json
          
      - name: Install dependencies
        run: |
          cd github-profile-3d-contrib
          npm ci
          
      - name: Build the tool
        run: |
          cd github-profile-3d-contrib
          npm run build
          
      - name: Generate 3D contribution graph
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: JeremyEltho
        run: |
          cd github-profile-3d-contrib
          node . $USERNAME
          
      - name: Copy generated files to assets
        run: |
          # Create assets directory if it doesn't exist
          mkdir -p assets
          
          # Copy all generated SVG files to assets
          if [ -d "github-profile-3d-contrib/profile-3d-contrib" ]; then
            cp github-profile-3d-contrib/profile-3d-contrib/profile-*.svg assets/ 2>/dev/null || true
            
            # Use the green animated version as the main one, fallback to green static
            if [ -f "github-profile-3d-contrib/profile-3d-contrib/profile-green-animate.svg" ]; then
              cp github-profile-3d-contrib/profile-3d-contrib/profile-green-animate.svg assets/profile-3d-contrib.svg
            elif [ -f "github-profile-3d-contrib/profile-3d-contrib/profile-green.svg" ]; then
              cp github-profile-3d-contrib/profile-3d-contrib/profile-green.svg assets/profile-3d-contrib.svg
            fi
            
            echo "Generated files:"
            ls -la assets/profile-*.svg
          else
            echo "No profile-3d-contrib directory found"
            exit 1
          fi
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the generated files
          git add assets/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update 3D contribution graph - $(date +'%Y-%m-%d')"
            git push
            echo "Successfully updated 3D contribution graph"
          fi
